runtime: nodejs
env: flex

handlers:
    - url: /static
      static_dir: build/static
  
    - url: /(.*\.(json|ico|js))$
      static_files: build/\1
      upload: build/.*\.(json|ico|js)$
  
    - url: .*
      static_files: build/index.html
      upload: build/index.html

skip_files:
  - ^node_modules$
  - ^README\..*
  - ^package-lock.json
  - \.gitignore
  - \.es*
  - ^\.git$
  - ^errors\.log
  - ^docker$